[build]
# Default build config
target = "aarch64-apple-darwin"

[target.bpfel-unknown-unknown]
# Solana BPF target config
rustflags = [
    "-C", "link-arg=-z",
    "-C", "link-arg=stack-size=65536",
    "-C", "link-arg=--stack-first",
]

# macOS native target config (no unsupported linker flags)
[target.aarch64-apple-darwin]
rustflags = [
    # Remove problematic flags for macOS
] 